### ISSUE TITLE
Do we need HTTPS to safely send accessCodes?

### ISSUE THREAD

**Issue by r-jsv** [cthit/VoteIT#17]

**Comment by lindskogen** [comment]
Yes

**Comment by Edholm** [comment]
See #23 for reason why. However, I think the server should encrypt messages also and not blindly trust HTTPS. 

I imagine a public/private key solution where the key is generated and distributed at each meeting. Preferably a eliptic curve algorithm. Their keys are very small compared to RSA for example.

**Comment by lindskogen** [comment]
Conclusion: We need HTTPS and perhaps implement additional encryption layer suggested in #23
