### ISSUE TITLE
Clients can see questions without a valid code, if their frontend is modified.

### ISSUE THREAD

**Issue by r-jsv** [cthit/VoteIT#19]
If a client modifies the frontend code, it can gain access to the questions and their answers. The client is not able to answer the question however. Is this a problem?

**Comment by Dr-Horv** [comment]
How can you gain access to the questions and answer if you do not have a valid access code?

**Comment by r-jsv** [comment]
Because the code:

"var es = new EventSource("/sse");
es.onmessage = function (event) {...}"

can be injected to 'index.ejs' and used to establish a SSE connection, even though the client hasn't passed the login step. The client will then get information regarding the newly created questions sent via the SSE connection, since there is no authentication before the connection is established.

**Comment by Dr-Horv** [comment]
I see. I think it is bad that we supply more information than the user should have access too. Upon connection there should be some sort of handshaking validating the accessCode before sending out a question.

**Comment by r-jsv** [comment]
Yes, it's not optimal. It won't however be accessible to users who don't have good programming knowledge. In previous versions there existed a handshake, but it was removed since the accessCode was sent via a query string, which is considered bad practise. We could investigate if there is another way to perform the handshake that is much more secure.

**Comment by r-jsv** [comment]
I should point out that they can't access the given answers (what people have voted on) but the available answers to choose among.

**Comment by lindskogen** [comment]
Why not just encapsulate it away from the global scope so the methods no longer are accessible?

**Comment by r-jsv** [comment]
Can you provide a code example to clarify what you mean?

**Comment by lindskogen** [comment]
http://stackoverflow.com/a/2421949/823725

**Comment by r-jsv** [comment]
The problem isn't that the backend has public methods, it's that the code used in vote.ejs can be injected into the index.ejs file. This would allow a user to establish the SSE connection before passing the accessCode validation step. So the backend need some handshake logic based on the accessCode before a connection is created.

**Comment by Dr-Horv** [comment]
I'd say this is not an issue, anyone on a meeting / reading the irc can know the question as it is.
