### ISSUE TITLE
Use different method for access code generation

### ISSUE THREAD

**Issue by Dr-Horv** [cthit/VoteIT#20]
At the moment we generate our own access codes using Math.random known to be predictable as shown in: http://franklinta.com/2014/08/31/predicting-the-next-math-random-in-java/

We should make use of some hashing method such as base64 to generate the accessCodes and include a secret part which should be unkown to others aswell as perhaps include the time of generation so:

hash64(accessCodePart1 ++ SECRET ++ accessCodePart2 ++ TimeRightNow)
-> YWNjZXNzQ29kZVBhcnQxU0VDUkVUYWNjZXNzQ29kZVBhcnQyMTQyODIzNzk2OA==

**Comment by Dr-Horv** [comment]
Using https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues and remotely generating the codes should resolve this issue.

**Comment by lindskogen** [comment]
The [Web Cryptography API](https://dvcs.w3.org/hg/webcrypto-api/raw-file/tip/spec/Overview.html#RandomSource-method-getRandomValues) is generating cryptographically random values.
