### ISSUE TITLE
Everything is sent in plaintext allows for sniping access codes

### ISSUE THREAD

**Issue by Rawa** [cthit/VoteIT#23]
When enter first entering the access code it is sent in plain text to server. This enables for malicious users to automatically grab access codes and vote before the intended user has the possibility to do so.

Also since votes are sent in plain text which allows for users to count votes and gather statistics on the result before presented.

This is especially true if any user is connected to nomad, since the network is unprotected.

We propose the use of public encryption scheme with padding to hide the answers of the users.

// @Edholm && @Rawa

**Comment by bark** [comment]
The real thing is going o over ssl whit Heroku SSL(TLS1.2 AES_128_GCM) aka good shit. So own encryption is not needed.
