### ISSUE TITLE
Save the enviroment

### ISSUE THREAD

**Issue by JonathanThunberg** [cthit/VoteIT#29]
When generating new codes, the votesession should reset to not print unusable codes.

**Comment by lindskogen** [comment]
Remove old codes when generating new? Fixed in `code-cleaning` :smiley:

**Comment by bark** [comment]
@lindskogen closed?

**Comment by lindskogen** [comment]
Needs more investigation

**Comment by Dr-Horv** [comment]
Unclear / not an issue any more.
