### ISSUE TITLE
Show explanation - what does candidates selected mean?

### ISSUE THREAD

**Issue by lindskogen** [cthit/VoteIT#30]
Example:

Votes available: 4
- [x] Mr 1
- [ ] Mr 2
- [x] Mr 3
- [x] Vacant1
- [ ] Vacant2

> You're voting for Mr 1, Mr 3. 
> Set 1 seat vacant.
> And 1 blank vote

**Comment by Dr-Horv** [comment]
Closed in https://github.com/cthit/VoteIT/commit/4574d2327062d67f143169d6b93cb2092cc98b97
