### ISSUE TITLE
Printouts are inconsistent

### ISSUE THREAD

**Issue by abjugard** [cthit/VoteIT#37]
Printing with number of codes per user being something other than 20 breaks formatting and causes code lists to be split by page breaks.

Furthermore, printing using Google Chromes printing interface causes the same thing to happen even with 20 codes per user.

**Comment by Edholm** [comment]
Also, more whitespace between each code-column to make it easy for those with an unsteady hand to cut them out (alcoholics and Michael J. Fox)

**Comment by abjugard** [comment]
Eloquent as usual Mr. Edholm.

**Comment by Edholm** [comment]
Must be why I'm known as Mr Eloquent in certain circles :+1:

**Comment by Dr-Horv** [comment]
Check if https://github.com/cthit/VoteIT/tree/bugfix/print-formatting maybe solves this problem
