### ISSUE TITLE
The symbols Il1 are very similar

### ISSUE THREAD

**Issue by vidare** [cthit/VoteIT#39]
Why don't we remove the characters I, L, 1 (both lower and uppercase) (Lima, India, One) from the generated voting codes. It is easily possible to get the mixed up. The reduced security is minimal in comparison to the increased usabillity.

**Comment by lindskogen** [comment]
Actually we've already thought about that, the only characters possible are: `123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz`, that means: no uppercase `I`, no lowercase `l`, just the number `1`

Same with `oO0` only lowercase `o` is possible.

https://github.com/cthit/VoteIT/blob/master/src/utils.js#L4

**Comment by vidare** [comment]
That is true, but the question arose during the meeting today. If my recommendation should be implemented this will not happen again. Is there a reason not to make the user experience better at no greater cost at all?

**Comment by lindskogen** [comment]
Maybe I misunderstood, your point is to remove all three of them entirely?

**Comment by vidare** [comment]
Yes, none of the letters at all. If there are any possibility of getting them wrong the user can be confused/loose confidence in the system, especially if an an unnecessary uncertanity is introduced. Today's mishap excluded, I would like to minimize the uncertanity involved in the voting process to a minimum. Hopefully y'all councure.

**Comment by lindskogen** [comment]
@bark any thoughts? what repercussions would removing `1` and `o` have?

**Comment by bark** [comment]
Not large at all, we are still in the the limit if we remove 1 and o if we use 9 letters long passwords.

**Comment by lindskogen** [comment]
Perfect!
