### ISSUE TITLE
Heroku timeout

### ISSUE THREAD

**Issue by Dr-Horv** [cthit/VoteIT#49]
When no web requests are made to heroku the instances "sleeps" and the state is lost and new code have to be generated.

**Comment by lindskogen** [comment]
> "SLEEPS AFTER 30 MINS OF INACTIVITY"
> Source: https://www.heroku.com/pricing

**Comment by bark** [comment]
Is this a problem? what do you mean with state is lost?

**Comment by lindskogen** [comment]
Application "sleeps" which makes it lose its internal state. - Is codes generated, and so on.

This actually happened during the last meeting

**Comment by bark** [comment]
hmm, yea that is a problem, can wee poke it every 10 minutes? or have some process that always work? or premium?

**Comment by lindskogen** [comment]
Yeah, we were planning on testing the health-check endpoint tomorrow :)

**Comment by lindskogen** [comment]
Ok, after some testing, the app actually seems to sleep after 30 min and all state is lost.

We were able to keep it alive using the following script:

``` bash
while true; do
    curl -s https://$SERVERNAME/health-check
    sleep 60
done;
```

Adding a note to the readme file
